myapp/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path("", views.index, name="index"),
    path("post/<str:post_id>", views.detail, name="detail"),
    path("new_url", views.new_url_view, name="new_page_url"),
    path("old_url", views.old_url_redirect, name="old_url"),
]   

myapp/myapp/urls.py
from django.contrib import admin
from django.urls import path, include

handler404 = 'myapp.views.custom_page_not_found'

urlpatterns = [
    path("blog/", include("blog.urls")),
    path('admin/', admin.site.urls),
]

myapp/blog/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    img_url = models.URLField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

myapp/blog/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.urls import reverse
import logging

# Create your views here.
posts = [
        {'id':1,'title':'Post1','content':'Some content example of Post1'},
        {'id':2,'title':'Post2','content':'Some content example of Post2'},
        {'id':3,'title':'Post3','content':'Some content example of Post3'},
        {'id':4,'title':'Post4','content':'Some content example of Post4'},
        {'id':5,'title':'Post5','content':'Some content example of Post5'},
    ]

def index(request):
    blog_title = 'Latest Posts'
    return render(request,'blog/index.html',{'blog_title':blog_title,'posts':posts})

def detail(request, post_id):
    post = next((item for item in posts if item['id'] == int(post_id)), None)
    # logger = logging.getLogger("TESTING")
    # logger.debug(f'post variable is {post}')
    return render(request,'blog/detail.html',{'post':post})

def old_url_redirect(request):
    return redirect(reverse('blog:new_page_url'))

def new_url_view(request):
    return HttpResponse("This is new url")

myapp/myapp/views.py
from django.shortcuts import render 

def custom_page_not_found(request,exception):
    return render(request,'404.html',status=404)

myapp/blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{blog_title}}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'blog/style.css' %}">
</head>
<body >
    <!-- header -->
     {% include 'blog/includes/header.html' %}

    <!-- dynamiv layout -->
    {% block content %}
    {% endblock %}

    <!-- footer -->
    {% include 'blog/includes/footer.html' %}
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

myapp/blog/templates/blog/detail.html
{% extends 'blog/base.html' %}

{% block content %}
  <div class="container-fluid ">
        
          <div class="row">
              <div class="col-lg-8">
                <h1 class="mb-4">{{post.title}} <small style="font-size:18px">({{post.category.name}})</small></h1>
                <p class="text-muted">Posted on {{post.created_at|date:"F j, Y"}}</p>
                <img src="{{post.img_url}}" class="img-fluid mb-4" alt="Blog Image">
                <p>{{post.content}}</p>
              </div>
              <div class="col-lg-4">
                <div class="card mt-3">
                  <div class="card-body">
                    <h5 class="card-title">Related Posts</h5>
                    <ul class="list-unstyled">
                      {% for related_post in related_posts %}
                      <li><a href="{% url 'blog:detail' slug=related_post.slug %}">{{related_post.title}}</a></li>
                      {% endfor%}
                    </ul>
                  </div>
                </div>
              </div>
          </div>
  </div>
{% endblock %}

myapp/blog/templates/blog/includes/footer.html
<footer class="bg-dark text-light p-3 fixed-bottom">
    <div class="col-4 d-flex justify-content-center align-items-center">
      <span class="text-light">© 2021 Company, Inc</span>
    </div>
</footer>

myapp/blog/templates/blog/includes/header.html
<header class="p-3 bg-dark text-white">
    <div class="row">
        <div class="col">
            <h3>Blog</h3>
        </div>
        <div class="col">
            <div class="d-flex justify-content-center gap-3">
                <a class="text-light text-decoration-none" href="">Home</a>
                <a class="text-light text-decoration-none" href="">About</a>
                <a class="text-light text-decoration-none" href="">Contact</a>
            </div>
        </div>
    </div>
</header>

myapp/blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="container-fluid ">
        <div class="row">
            <h2 >{{blog_title}}</h2>
        </div>
            <div class="row m-3">
                {% if posts %}
                {% for post in posts %}
                <div class="col-4 mb-4">
                    <div class="card">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-4">
                                    <img src="https://via.placeholder.com/300" class="img-fluid" alt="...">
                                </div>
                                <div class="col-md-8">
                                    <h5 class="card-title">{{post.title}}</h5>
                                    <p class="card-text">{{post.content}}</p>
                                    <div class="d-flex justify-content-between">
                                        <a href="{% url 'blog:detail' post_id=post.id %}">Read More</a>
                                        <a class="text-decoration-none text-dark fw-bold" href="#">Sports</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
                {% else %}
                    <p>No Posts Available</p>
                {% endif %}
                
                <div class="col-12 my-3">
                    <nav aria-label="Page navigation">
                        <ul class="pagination">
                            <li class="page-item">
                                <a class="page-link" href="?page=1" aria-label="First">
                                    <span aria-hidden="true">&laquo; first</span>
                                </a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="?page=1" aria-label="Previous">
                                    <span aria-hidden="true">previous</span>
                                </a>
                            </li>
                            <li class="page-item"><span class="page-link">Page 3 of 20.</span></li>
                            <li class="page-item">
                                <a class="page-link" href="?page=4" aria-label="Next">
                                    <span aria-hidden="true">next</span>
                                </a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="?page=20" aria-label="Last">
                                    <span aria-hidden="true">last &raquo;</span>
                                </a>
                            </li>
                        </ul>
                    </nav>
                    
                </div>
            </div>
            <div class="row">
            
            </div>
            
    </div>
{% endblock %}